services:
    app.github.client_description:
        class: GuzzleHttp\Command\Guzzle\Description
        factory: 'App\Factory\ClientDescriptionFactory:create'
        arguments:
            -
                baseUri: 'https://api.github.com/'
                headers:
                    Accept: 'application/vnd.github.v3+json'
                operations:
                    getPaginatedIssues:
                        httpMethod: 'GET'
                        uri: '/issues?page={page}&per_page={per_page}&state={state}'
                        parameters:
                            page:
                                location: uri
                                type: integer
                                required: true
                            per_page:
                                location: uri
                                type: integer
                                required: true
                            state:
                                location: uri
                                type: string
                                required: true
                    getSingleIssue:
                        httpMethod: 'GET'
                        uri: '/repos/{owner}/{repo}/issues/{number}'
                        parameters:
                            owner:
                                location: uri
                                type: string
                                required: true
                            repo:
                                location: uri
                                type: string
                                required: true
                            number:
                                location: uri
                                type: integer
                                required: true
                    getIssueComments:
                        httpMethod: 'GET'
                        uri: '/repos/{owner}/{repo}/issues/{number}/comments'
                        parameters:
                            owner:
                                location: uri
                                type: string
                                required: true
                            repo:
                                location: uri
                                type: string
                                required: true
                            number:
                                location: uri
                                type: integer
                                required: true

    app.github.client:
        class: App\Client\GithubClient
        public: true
        factory: 'App\Factory\GithubClientFactory:create'
        arguments:
            - '@app.github.client_description'
            - '@App\Manager\GithubUserManager'
            - '%kernel.cache_dir%'

    app.github.repository:
        class: App\Repository\GithubRepository
        public: true
        arguments:
            - '@app.github.client'

    app.github.data_manager:
        class: App\Manager\GithubDataManager
        public: true
        arguments:
            - '@app.github.repository'
            - '@App\Client\GithubResponseMediator'

    app.github.paginated_data_manager:
        class: App\Manager\GithubPaginatedDataManager
        public: true
        arguments:
            - '@app.github.repository'
            - '@App\Client\GithubResponseMediator'
            - '@App\Factory\FixedPagerFactory'
            - '%env(ISSUES_PER_PAGE)%'
