version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - $PWD:/app
      - ./webserver.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    image: php:7.1-fpm
    volumes:
      - $PWD:/app
