github_oauth:
    resource: App\Controller\GithubOauthController
    type: annotation
    prefix: /connect

logout:
    path: /logout

login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: login.html.twig

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app.issue.list_issues
        permanent: true

issue_controller:
    resource: App\Controller\IssueController
    type: annotation
    prefix: /issue
